#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 25 19:34:14 2025

@author: irvinam
"""

from boutdata.collect import collect
from boutdata.data import BoutData
from boututils.datafile import DataFile
import warnings
import os
import sys
from pathlib import Path
import matplotlib.patches as patches

import numpy as np
import matplotlib.pyplot as plt
import numpy.ma as ma
from BoutPlot_interactive import InteractivePlot
import matplotlib.colors as mcolors
import argparse
import time
from PlotPDF import to_pdf
from PlotPNG import to_png
import datetime

def find_file(target):
    return next(Path('.').rglob(target), None)

def str2bool(v):
    if isinstance(v, bool):
        return v
    if v.lower() in ('yes', 'true', 't', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')

if __name__ == "__main__":
    
    default_vars = ["Ni","Ti","Te"]#,"Vexbx", "Vexby", "Vexbz", "Vbtildx", "Vbtildy", "Vbtildz","phi","Psi"]#, "Ve0_diax", "Ve0_diay", "Ve0_diaz"]
    
    ### Verify data file names and locations ###
    parser = argparse.ArgumentParser(prog="plot_matrix_masks",description='Plotting inputs for matrix masks')
    parser.add_argument("-p", "--path", type=Path, default=Path("."), help="The path to the data directory (NOT THE NUMPY DIRECTORY).\n(default: \"%(default)s\"")
    parser.add_argument("-g","--grid", type=Path, default=Path("d3d_184016.3200_psi092108_nx260ny64.nc"), help="The grid file name, assumes the grid is in the data directory.\n(default: \"%(default)s\"")   
    parser.add_argument("-v","--vars", nargs="*", default=default_vars, help="Variables from BOUT++ to be saved.\n(default: %(default)s")
    parser.print_help()
    args = parser.parse_args()
    
    # If running as a script on the cluster
    data_dir = args.path
    # Extract the bout grid name from the input file, expanding $BGRIDS alias is present
    with open("BOUT.inp") as f:
        for line in f:
            if "grid =" in line:
                start = line.find('"') + 1
                end = line.rfind('"')
                path_with_BGRIDS = line[start:end]  # Extract string inside quotes
                grid_fname = Path(os.path.expandvars(path_with_BGRIDS))
                break  # Stop after first match


    print(f"Using data_dir: {data_dir}")
    print(f"Using grid: {grid_fname}")

    numpy_dir = data_dir / "numpy"
    if not os.path.isdir(numpy_dir):
        print(f"'{numpy_dir}' does not exist. Please run BoutSaveData to create '{numpy_dir}' first.")
        raise ValueError(f"Did not find numpy folder in {data_dir}!")
    
    vars_to_be_plotted=[] # used to eliminate vars that were not found in the save file dirs
    for var in args.vars:
        data_file = numpy_dir / (var + ".npy")
        if not os.path.isfile(data_file) :
            print(f"Did not find {var} in {numpy_dir}!!")
            warnings.warn(f"Did not find {var} in {numpy_dir} required to make plots!! Run 'bout_save_data'")
        else:
            vars_to_be_plotted.append(var)
            
    if len(vars_to_be_plotted) == 0:
        raise ValueError(f"No requested variables found in the {numpy_dir} folder! Exiting...")
            
    ### Collect relevant data to make plots ###
    
    # Collect grid quantities
    d = BoutData(path=data_dir)
    nt = d["outputs"]["Ni"].shape[0]
    nx = d["outputs"]["Ni"].shape[1]
    ny = d["outputs"]["Ni"].shape[2]
    nz = d["outputs"]["Ni"].shape[3]
    
    t = range(0,nt)
    x = range(0,nx)
    y = range(0,ny)
    z = range(0,nz)

    with DataFile(str(grid_fname)) as g:
        Rxy = g["Rxy"]
        Zxy = g["Zxy"]
        Bpxy = g["Bpxy"]
        Btxy = g["Btxy"]
    
    matrices = []
    for var in vars_to_be_plotted:
        matrices.append(np.load(numpy_dir / (var+".npy")))

    #try:

    def function(plot_var,sliders):
            return plot_var[:,int(sliders[0].val)-1,int(sliders[1].val)-1,int(sliders[2].val)-1]

    time_series = InteractivePlot(function,t,matrices,[x,y,z],'t',args.vars,['ix','jy','z']) # plot vars should be tuple or list of tuples !!!

    #except:
     #   print('Cannot plot variables with no time dependence.')

        
